//! Wavetable generation and FFT-based band limiting.
//!
//! The wavetable is a fixed-size oversampled single-cycle waveform stored
//! as `[f32; WAVETABLE_SIZE]`. It is generated by evaluating a user script
//! across the phase range, normalizing, removing DC offset, and optionally
//! applying band limiting via FFT.
//!
//! # Band limiting approach
//!
//! 1. Forward real FFT of the wavetable → complex spectrum
//! 2. Zero out harmonics above the bandwidth limit
//! 3. Inverse real FFT → band-limited waveform
//! 4. Re-normalize

use realfft::RealFftPlanner;
use rustfft::num_complex::Complex;
use std::sync::Arc;

/// Number of samples in the wavetable. Must be a power of two for FFT.
pub const WAVETABLE_SIZE: usize = 2048;

/// A shareable, immutable wavetable.
pub type SharedWavetable = Arc<Box<[f32; WAVETABLE_SIZE]>>;

/// Number of samples in the oscilloscope ring buffer.
pub const SCOPE_SIZE: usize = 1024;

/// Default sine-based wavetable.
pub fn default_wavetable() -> Box<[f32; WAVETABLE_SIZE]> {
    let mut data = Box::new([0.0f32; WAVETABLE_SIZE]);
    for (i, s) in data.iter_mut().enumerate() {
        let phase = (i as f32 / WAVETABLE_SIZE as f32) * 2.0 * std::f32::consts::PI;
        *s = phase.sin();
    }
    data
}

/// Generate a wavetable from a sampling function `f(x)` where x ranges from
/// 0 to 2π. Returns the raw, unprocessed waveform.
pub fn sample_waveform<F: Fn(f32) -> f32>(f: F) -> Box<[f32; WAVETABLE_SIZE]> {
    let mut data = Box::new([0.0f32; WAVETABLE_SIZE]);
    for (i, s) in data.iter_mut().enumerate() {
        let x = (i as f32 / WAVETABLE_SIZE as f32) * 2.0 * std::f32::consts::PI;
        *s = f(x);
    }
    data
}

/// Remove DC offset in-place.
pub fn remove_dc(data: &mut [f32; WAVETABLE_SIZE]) {
    let sum: f32 = data.iter().sum();
    let mean = sum / WAVETABLE_SIZE as f32;
    for s in data.iter_mut() {
        *s -= mean;
    }
}

/// Normalize waveform so peak amplitude is 1.0.
pub fn normalize(data: &mut [f32; WAVETABLE_SIZE]) {
    let mut peak = 0.0f32;
    for s in data.iter() {
        let abs = s.abs();
        if abs > peak {
            peak = abs;
        }
    }
    if peak > 1e-10 {
        let scale = 1.0 / peak;
        for s in data.iter_mut() {
            *s *= scale;
        }
    }
}

/// Apply FFT-based low-pass filtering to the wavetable.
///
/// `max_harmonics` is the maximum number of harmonics to preserve.
/// For a wavetable of size N, there are N/2 frequency bins.
pub fn band_limit(data: &mut [f32; WAVETABLE_SIZE], max_harmonics: usize) {
    let max_bin = max_harmonics.min(WAVETABLE_SIZE / 2);

    // Set up FFT planner.
    let mut planner = RealFftPlanner::<f32>::new();
    let fwd = planner.plan_fft_forward(WAVETABLE_SIZE);
    let inv = planner.plan_fft_inverse(WAVETABLE_SIZE);

    // Forward FFT: real -> complex.
    let mut spectrum = fwd.make_output_vec();
    let mut scratch = fwd.make_scratch_vec();
    let mut input = data.to_vec();
    fwd.process_with_scratch(&mut input, &mut spectrum, &mut scratch)
        .unwrap();

    // Zero out bins above max_harmonics.
    for i in spectrum.iter_mut().skip(max_bin) {
        *i = Complex::new(0.0, 0.0);
    }

    // Inverse FFT: complex -> real.
    let mut output = inv.make_output_vec();
    let mut scratch_inv = inv.make_scratch_vec();
    inv.process_with_scratch(&mut spectrum, &mut output, &mut scratch_inv)
        .unwrap();

    // Copy back and normalize (IFFT introduces scaling).
    let scale = 1.0 / WAVETABLE_SIZE as f32;
    for (i, s) in data.iter_mut().enumerate() {
        *s = output[i] * scale;
    }
}

/// Full wavetable generation pipeline:
/// 1. Sample the function at 2048 points
/// 2. Remove DC offset
/// 3. Normalize
/// 4. Band limit (keeping harmonics up to ~200 for smooth sound)
/// 5. Normalize again
pub fn generate_wavetable<F: Fn(f32) -> f32>(f: F) -> SharedWavetable {
    let mut data = sample_waveform(f);
    remove_dc(&mut data);
    normalize(&mut data);

    // Band-limit to a reasonable harmonic count for a high-quality oscillator.
    // 200 harmonics at 44.1 kHz covers up to ~4.3 kHz at the fundamental,
    // which is musically useful across most of the keyboard.
    band_limit(&mut data, 200);
    normalize(&mut data);

    Arc::new(data)
}

/// Quick generation without band-limiting (for preview purposes).
pub fn generate_raw<F: Fn(f32) -> f32>(f: F) -> SharedWavetable {
    let mut data = sample_waveform(f);
    remove_dc(&mut data);
    normalize(&mut data);
    Arc::new(data)
}
